language: node_js
node_js:
  - 12

jobs:
fast_finish: true
allow_failures:
  - env: EMBER_VERSION=release
  - env: EMBER_VERSION=beta
  - env: EMBER_VERSION=canary

cache:
  directories:
      - node_modules

install:
  - npm install

before_script:
 
script:
  - npm run lint
  - npm run build